# Scaffolding generated by Casein v5.1.1.5

module Casein
  class PagesController < Casein::CaseinController
    before_filter :load_page, :only => [:show, :update, :destroy]
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Pages'
      @pages = Page.order(sort_order(:title)).paginate :page => params[:page]
      respond_to do |format|
        format.html
        format.csv { send_data @pages.to_csv, filename: "pages-#{Date.today}.csv"}
        format.xlsx
      end
    end
  
    def show
      @casein_page_title = 'View page'
    end
  
    def import
      Page.import(params[:file])
      flash[:notice] = 'File has been imported'
      redirect_to casein_pages_path
    end

    def new
      @casein_page_title = 'Add a new page'
      @page = Page.new
    end

    def create
      @page = Page.new page_params
    
      if @page.save
        flash[:notice] = 'Page created'
        redirect_to casein_pages_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new page'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update page'
      
      respond_to do |format|
          if params[:submit]
        if @page.update_attributes page_params
          
            @page.submit!
          elsif params[:approve]
            @page.approve!
          elsif params[:reject]
            @page.reject!
          elsif params[:publish]
            @page.publish!
          elsif params[:unpublish]
            @page.unpublish!
          end
        
          format.html { redirect_to casein_page_path(@page), notice: "Page has been updated. #{undo_link}" }
          format.js
        else
          flash.now[:warning] = 'There were problems when trying to update this page'
          render :action => :show
        end
     end
    end
    
    def edit_multiple
      @pages = Page.where(id: page_params[:page_ids])

      if params[:edit]
        render "pages/edit_multiple"
      elsif params[:unpublish]
        @pages.each do |page|
          page.unpublish! if page.published?
        end
        redirect_to casein_pages_path
      elsif params[:publish]
        @pages.each do |page|
          page.publish! if !page.published?
        end
          redirect_to casein_pages_path
      elsif params[:delete]
          @pages.destroy_all
          redirect_to casein_pages_path
      end
    end

    def update_multiple
     @pages = Page.friendly.update(params[:pages].keys, params[:pages].values)
      @pages.reject! { |page| page.errors.empty? }
      if @pages.empty?
        redirect_to casein_pages_path
      else
        render "pages/edit_multiple"
      end
    end
 
    def destroy

      @page.destroy
      flash[:notice] = 'Page has been deleted. #{undo_link}"'
      redirect_to casein_pages_path
    end
  
    private
      
      def page_params
        params.require(:page).permit(:title, :feature, :feature_image, :workflow_state, :type, :content, :published_at, :ancestry, :created_at, :published_at)
      end
      
      def undo_link
        view_context.link_to("undo", revert_version_path(@page.versions.last), :method => :post).html_safe
      end
      
      def load_page
        @page = Page.friendly.find params[:id]
      end
  
  end
end
